# Global LLM configuration
[llm]
model = "claude-3-5-sonnet-20241022"
base_url = "https://aihubmix.com/v1"
api_key = "sk-foSNwPKU3gM2F19XBb85B99cF7394825Af43Ad468dB6B710"
max_tokens = 8192
temperature = 0.0

# [llm] #AZURE OPENAI:
# api_type= 'azure'
# model = "YOUR_MODEL_NAME" #"gpt-4o-mini"
# base_url = "{YOUR_AZURE_ENDPOINT.rstrip('/')}/openai/deployments/{AZURE_DEPOLYMENT_ID}"
# api_key = "AZURE API KEY"
# max_tokens = 8096
# temperature = 0.0
# api_version="AZURE API VERSION" #"2024-08-01-preview"

# Optional configuration for specific LLM models
[llm.vision]
model = "claude-3-5-sonnet-20241022"
base_url = "https://aihubmix.com/v1"
api_key = "sk-foSNwPKU3gM2F19XBb85B99cF7394825Af43Ad468dB6B710"
max_tokens = 8192
temperature = 0.0

# Server configuration
[server]
host = "localhost"
port = 5172
